apiVersion: spdx.softwarecomposition.kubescape.io/v1beta1
kind: ApplicationProfile
metadata:
  annotations:
    kubescape.io/completion: complete
    kubescape.io/instance-id: apiVersion-apps/v1/namespace-default/kind-ReplicaSet/name-webapp-d87cdd796
    kubescape.io/resource-size: "250"
    kubescape.io/status: completed
    kubescape.io/wlid: wlid://cluster-honeycluster/namespace-default/deployment-webapp
  creationTimestamp: "2025-05-01T14:48:24Z"
  labels:
    kubescape.io/instance-template-hash: d87cdd796
    kubescape.io/workload-api-group: apps
    kubescape.io/workload-api-version: v1
    kubescape.io/workload-kind: Deployment
    kubescape.io/workload-name: webapp
    kubescape.io/workload-namespace: default
    kubescape.io/workload-resource-version: "1249020"
  name: replicaset-webapp-d87cdd796
  namespace: default
  resourceVersion: "3"
  uid: cbbadf27-372f-40c3-9285-47b3b149ea9b
spec:
  architectures:
  - amd64
  containers:
  - capabilities:
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
    endpoints:
    - direction: inbound
      endpoint: :8080/ping.php
      headers:
        Host:
        - localhost:8080
      internal: false
      methods:
      - GET
    - direction: inbound
      endpoint: :80/
      headers:
        Connection:
        - keep-alive
        Host:
        - 87.238.55.40
      internal: false
      methods:
      - GET
    execs:
    - args:
      - /bin/rm
      - -f
      - /var/run/apache2/apache2.pid
      path: /bin/rm
    - args:
      - /usr/local/bin/apache2-foreground
      path: /usr/local/bin/apache2-foreground
    - args:
      - /bin/sh
      - -c
      - 'ping -c 4 '
      path: /bin/sh
    - args:
      - /bin/sh
      - -c
      - ping -c 4 172.16.0.2
      path: /bin/sh
    - args:
      - /usr/bin/dirname
      - /var/run/apache2
      path: /usr/bin/dirname
    - args:
      - /usr/sbin/apache2
      - -DFOREGROUND
      path: /usr/sbin/apache2
    - args:
      - /usr/bin/dirname
      - /var/log/apache2
      path: /usr/bin/dirname
    - args:
      - /bin/mkdir
      - -p
      - /var/log/apache2
      path: /bin/mkdir
    - args:
      - /bin/mkdir
      - -p
      - /var/run/apache2
      path: /bin/mkdir
    - args:
      - /bin/ping
      - -c
      - "4"
      path: /bin/ping
    - args:
      - /usr/local/bin/docker-php-entrypoint
      - apache2-foreground
      path: /usr/local/bin/docker-php-entrypoint
    - args:
      - /usr/bin/dirname
      - /var/lock/apache2
      path: /usr/bin/dirname
    - args:
      - /bin/ping
      - -c
      - "4"
      - 172.16.0.2
      path: /bin/ping
    - args:
      - /bin/mkdir
      - -p
      - /var/lock/apache2
      path: /bin/mkdir
    identifiedCallStacks: null
    imageID: ghcr.io/k8sstormcenter/webapp@sha256:e323014ec9befb76bc551f8cc3bf158120150e2e277bae11844c2da6c56c0a2b
    imageTag: ghcr.io/k8sstormcenter/webapp@sha256:e323014ec9befb76bc551f8cc3bf158120150e2e277bae11844c2da6c56c0a2b
    name: ping-app
    opens:
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/apache2.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/conf-available/charset.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/conf-available/docker-php.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/conf-available/localized-error-pages.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/conf-available/other-vhosts-access-log.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/conf-available/security.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/conf-available/serve-cgi-bin.conf
    - flags:
      - O_CLOEXEC
      - O_DIRECTORY
      - O_NONBLOCK
      - O_RDONLY
      path: /etc/apache2/conf-enabled
    - flags:
      - O_RDONLY
      path: /etc/apache2/envvars
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/access_compat.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/alias.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/alias.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/auth_basic.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/authn_core.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/authn_file.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/authz_core.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/authz_host.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/authz_user.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/autoindex.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/autoindex.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/deflate.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/deflate.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/dir.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/dir.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/env.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/filter.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/mime.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/mime.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/mpm_prefork.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/mpm_prefork.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/negotiation.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/negotiation.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/php7.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/reqtimeout.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/reqtimeout.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/setenvif.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/setenvif.load
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/status.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/mods-available/status.load
    - flags:
      - O_CLOEXEC
      - O_DIRECTORY
      - O_NONBLOCK
      - O_RDONLY
      path: /etc/apache2/mods-enabled
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/ports.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/apache2/sites-available/000-default.conf
    - flags:
      - O_CLOEXEC
      - O_DIRECTORY
      - O_NONBLOCK
      - O_RDONLY
      path: /etc/apache2/sites-enabled
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/gai.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/group
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/host.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/hosts
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/ld.so.cache
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/mime.types
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/nsswitch.conf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/passwd
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /etc/resolv.conf
    - flags:
      - O_RDONLY
      path: /etc/ssl/openssl.cnf
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libc-2.31.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libcap.so.2.44
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libcom_err.so.2.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libcrypt.so.1.1.0
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libdl-2.31.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libexpat.so.1.6.12
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libgcc_s.so.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libgpg-error.so.0.29.0
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libkeyutils.so.1.9
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/liblzma.so.5.2.5
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libm-2.31.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libnss_files-2.31.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libpcre.so.3.13.3
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libpthread-2.31.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libreadline.so.8.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libresolv-2.31.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libselinux.so.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libtinfo.so.6.2
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /lib/x86_64-linux-gnu/libz.so.1.2.11
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯
    - flags:
      - O_RDONLY
      path: /proc/⋯/kernel/ngroups_max
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯/mounts
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /proc/⋯/task/1/fd
    - flags:
      - O_CREAT
      - O_EXCL
      - O_RDWR
      path: /run/apache2/apache2.pid.J0lYog
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/libphp7.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_access_compat.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_alias.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_auth_basic.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_authn_core.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_authn_file.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_authz_core.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_authz_host.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_authz_user.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_autoindex.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_deflate.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_dir.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_env.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_filter.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_mime.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_mpm_prefork.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_negotiation.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_reqtimeout.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_setenvif.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/apache2/modules/mod_status.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libapr-1.so.0.7.0
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libaprutil-1.so.0.6.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libargon2.so.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libbrotlicommon.so.1.0.9
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libbrotlidec.so.1.0.9
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libcurl.so.4.7.0
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libffi.so.7.1.0
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libgcrypt.so.20.2.8
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libgmp.so.10.4.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libgnutls.so.30.29.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libhogweed.so.6.4
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libicudata.so.67.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libicuuc.so.67.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libidn2.so.0.3.7
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.11.5
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.11.5
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libnettle.so.8.4
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libnghttp2.so.14.20.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libonig.so.5.1.0
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.3.0
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libpcre2-8.so.0.10.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libpsl.so.5.3.2
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/librtmp.so.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libsodium.so.23.3.0
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libssh2.so.1.0.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libssl.so.1.1
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.28
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libtasn1.so.6.6.0
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libunistring.so.2.1.0
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libuuid.so.1.3.0
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.10
    - flags:
      - O_RDONLY
      path: /usr/local/bin/apache2-foreground
    - flags:
      - O_RDONLY
      path: /usr/local/bin/docker-php-entrypoint
    - flags:
      - O_CLOEXEC
      - O_DIRECTORY
      - O_NONBLOCK
      - O_RDONLY
      path: /usr/local/etc/php/conf.d
    - flags:
      - O_RDONLY
      path: /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/local/lib/php/extensions/no-debug-non-zts-20190902/sodium.so
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /usr/share/zoneinfo/Etc/UTC
    - flags:
      - O_CLOEXEC
      - O_RDONLY
      path: /var/www/html/index.html
    - flags:
      - O_RDONLY
      path: /var/www/html/ping.php
    rulePolicies:
      R0001: {}
      R0002: {}
      R0003: {}
      R0004: {}
      R0005: {}
      R0006: {}
      R0007: {}
      R0008: {}
      R0009: {}
      R0010: {}
      R0011: {}
      R1000: {}
      R1001: {}
      R1002: {}
      R1003: {}
      R1004: {}
      R1005: {}
      R1006: {}
      R1007: {}
      R1008: {}
      R1009: {}
      R1010: {}
      R1011: {}
      R1012: {}
      R1015: {}
      R1030: {}
    seccompProfile:
      spec:
        defaultAction: ""
    syscalls:
    - accept4
    - access
    - arch_prctl
    - bind
    - brk
    - capget
    - capset
    - chdir
    - chmod
    - clone
    - close
    - close_range
    - connect
    - dup2
    - dup3
    - epoll_create1
    - epoll_ctl
    - epoll_pwait
    - execve
    - exit
    - exit_group
    - faccessat2
    - fcntl
    - fstat
    - fstatfs
    - futex
    - getcwd
    - getdents64
    - getegid
    - geteuid
    - getgid
    - getpgrp
    - getpid
    - getppid
    - getrandom
    - getsockname
    - getsockopt
    - gettid
    - getuid
    - ioctl
    - listen
    - lseek
    - lstat
    - mkdir
    - mmap
    - mprotect
    - munmap
    - nanosleep
    - newfstatat
    - openat
    - pipe
    - pipe2
    - poll
    - prctl
    - prlimit64
    - read
    - recvfrom
    - recvmsg
    - rename
    - rt_sigaction
    - rt_sigprocmask
    - rt_sigreturn
    - select
    - sendto
    - set_robust_list
    - set_tid_address
    - setgid
    - setgroups
    - setitimer
    - setsockopt
    - setuid
    - shutdown
    - sigaltstack
    - socket
    - stat
    - statfs
    - sysinfo
    - tgkill
    - times
    - tkill
    - umask
    - uname
    - unlinkat
    - vfork
    - wait4
    - write
    - writev